### ISSUE TITLE
cli works but crashes at the end

### ISSUE THREAD

**Issue by dangelov** [Kilian/Trimage#70]
After running trimage with:
`trimage -d .`

It seems to successfully process all files, but ends with a crash:
```
Exception ignored in: <function Worker.__del__ at 0x7fd26857d9d0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/trimage/trimage.py", line 414, in __del__
  File "/usr/lib/python3.8/site-packages/trimage/ThreadPool/ThreadPool.py", line 172, in shutdown
TypeError: 'NoneType' object is not callable
```

Running the newest version, installed with `yay -S trimage` on Arch Linux.

**Comment by orende** [comment]
Can confirm, this is happening to me as well with trimage 1.0.6 and Python 3.8.5 on Ubuntu 20.04.1 LTS.

**Comment by diklimchuk** [comment]
I had the same issue, worked after buidling trimage from sources. This issue was fixed in #76 so it probably can be closed now.

**Comment by orende** [comment]
@diklimchuk The current version in the Ubuntu package repo is 1.0.6, which was released before the fix. So anyone installing from there will still experience the issue.

**Comment by rootwork** [comment]
Can we get a new release for Ubuntu?

Incidentally the "Download for Ubuntu" link on trimage.org is now broken; it gets redirected to snapcraft.io, and Trimage isn't there. (`apt install` still works)

**Comment by rootwork** [comment]
Oh, and it's confusing because when building from source, the version reported is still 1.0.6 -- would be helpful to get a version bump too.
