### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/file.png'

### ISSUE THREAD

**Issue by diklimchuk** [Kilian/Trimage#78]
In command line mode trimage fails to handle files with the same name in different directory.
Sample structure:
- root
 - one
  - image.png
 -two
  - image.png

command: `trimage -d root`

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/trimage/ThreadPool/ThreadPool.py", line 83, in execute
    return_value = self.callable(*self.arguments) #IGNORE:W0142
  File "/usr/local/lib/python3.9/site-packages/trimage/trimage.py", line 397, in compress
    remove(backupfullpath)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/image.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/trimage/ThreadPool/ThreadPool.py", line 124, in run
    job.execute()
  File "/usr/local/lib/python3.9/site-packages/trimage/ThreadPool/ThreadPool.py", line 86, in execute
    logger.warning("A job in the ThreadPool raised an exception: ", excep)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1648, in callHandlers
    if record.levelno >= hdlr.level:
AttributeError: '_io.TextIOWrapper' object has no attribute 'level'
```

Setup: Mac OS, trimage 1.0.6

**Comment by fostimus** [comment]
Same problem here

**Comment by trinitronx** [comment]
[Same error is reproducible][1] with the `trimage` Arch Linux AUR package.  When using `-f /path/to/file.png` or drag-n-drop in the GUI:

```console
$ trimage -f /tmp/test.png

Warning: versions are different between png.h and png.c
  png.h version: 1.6.37
  png.c version: 1.6.44

 pngcrush 1.8.13, uses libpng 1.6.37 and zlib 1.2.11
 Check http://pmt.sf.net/
 for the most recent version.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/trimage/ThreadPool/ThreadPool.py", line 90, in execute
    return_value = self.callable(*self.arguments) #IGNORE:W0142
  File "/usr/lib/python3.13/site-packages/trimage/trimage.py", line 381, in compress
    copy(self.fullpath, backupfullpath)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/shutil.py", line 428, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/shutil.py", line 240, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/tmp/test.png' and '/tmp/test.png' are the same file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/trimage/ThreadPool/ThreadPool.py", line 131, in run
    job.execute()
    ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/trimage/ThreadPool/ThreadPool.py", line 93, in execute
    logger.warning("A job in the ThreadPool raised an exception: ", excep)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1531, in warning
    self._log(WARNING, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1735, in callHandlers
    if record.levelno >= hdlr.level:
                         ^^^^^^^^^^
AttributeError: '_io.TextIOWrapper' object has no attribute 'level'

```

Another non-fatal exception happens when passing `-d dir-name/`:
(probably same issue as #70)

```console
$ trimage -d /tmp/test

Warning: versions are different between png.h and png.c
  png.h version: 1.6.37
  png.c version: 1.6.44

 pngcrush 1.8.13, uses libpng 1.6.37 and zlib 1.2.11
 Check http://pmt.sf.net/
 for the most recent version.
** Processing: /tmp/test/test.png
1910x1362 pixels, 4x8 bits/pixel, RGB+alpha
Input IDAT size = 566932 bytes
Input file size = 571072 bytes

Trying:
  zc = 9  zm = 9  zs = 0  f = 0     IDAT size = 436327
  zc = 9  zm = 8  zs = 0  f = 0     IDAT size = 435470
  zc = 9  zm = 9  zs = 0  f = 2     IDAT size = 431901
  zc = 9  zm = 8  zs = 0  f = 2     IDAT size = 431485

Selecting parameters:
  zc = 9  zm = 8  zs = 0  f = 2     IDAT size = 431485

Output IDAT size = 431485 bytes (135447 bytes decrease)
Output file size = 435217 bytes (135855 bytes = 23.79% decrease)

Warning: versions are different between png.h and png.c
  png.h version: 1.6.37
  png.c version: 1.6.44

  Recompressing IDAT chunks in /tmp/test/test.png to /tmp/test/test.png.bak
   Total length of data found in critical chunks            =    403298
   Best pngcrush method        =   7 (ws 15 fm 0 zl 9 zs 0) =    436384
CPU time decode 0.109618, encode 1.370095, other 0.006705, total 1.504558 sec
File: /tmp/test/test.png, Old Size: 557.7KB, New Size: 426.2KB, Ratio: 23.6%
Exception ignored in: <function Worker.__del__ at 0x7fe590dd76a0>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/trimage/trimage.py", line 414, in __del__
  File "/usr/lib/python3.13/site-packages/trimage/ThreadPool/ThreadPool.py", line 172, in shutdown
TypeError: 'NoneType' object is not callable

```

[1]: https://aur.archlinux.org/packages/trimage#comment-1007472
